// One-time dev script: downloads every subset of every world's faces from
// Google Fonts (all OFL licensed) into fonts/ and emits
// fonts/fonts.css with matching @font-face rules, so the app needs no CDN at
// runtime. Run: node scripts/fetch-fonts.js
'use strict';

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36';
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&family=Saira+Stencil+One&family=Archivo:wght@400;600;700&family=Archivo+Black&family=Archivo+Narrow:wght@400;500&family=Roboto+Mono:wght@400&family=Figtree:wght@400;500;700&family=Anton&family=Zilla+Slab:wght@400;600&family=Spectral:wght@400;600&display=swap';

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': UA } }, (res) => {
      if (res.statusCode !== 200) {
        res.resume();
        reject(new Error('HTTP ' + res.statusCode + ' for ' + url));
        return;
      }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    }).on('error', reject);
  });
}

(async () => {
  const css = (await get(CSS_URL)).toString('utf8');
  const outDir = path.join(__dirname, '..', 'fonts');
  fs.mkdirSync(outDir, { recursive: true });

  // Parse each @font-face block.
  const blocks = css.split('@font-face').slice(1);
  const faces = [];
  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i];
    const family = /font-family:\s*'([^']+)'/.exec(block);
    const src = /url\((https:[^)]+\.woff2)\)/.exec(block);
    const range = /unicode-range:\s*([^;]+);/.exec(block);
    const weight = /font-weight:\s*(\d+);/.exec(block);
    const style = /font-style:\s*([a-z]+);/.exec(block);
    if (!family || !src) continue;
    faces.push({
      family: family[1],
      url: src[1],
      range: range ? range[1].trim() : null,
      weight: weight ? weight[1] : '400',
      style: style ? style[1] : 'normal'
    });
  }

  // Google serves ONE resource for several requested weights of the same
  // family — the 400/600/700 rows of Archivo are byte-identical. Naming the
  // file after each CSS occurrence therefore vendored the same blob three
  // times under three names, and the stylesheet then treated them as separate
  // sources. Deduplicate twice: by URL, so an identical row is not fetched at
  // all, and by content hash, so two different URLs serving the same bytes
  // still land in one file that several @font-face rules point at.
  const byUrl = new Map();
  const byHash = new Map();
  let unique = 0;

  async function fileFor(face) {
    const cached = byUrl.get(face.url);
    if (cached) return cached;

    const data = await get(face.url);
    const hash = crypto.createHash('sha256').update(data).digest('hex');
    const seen = byHash.get(hash);
    if (seen) {
      byUrl.set(face.url, seen);
      console.log('reused  fonts/' + seen + ' for ' + face.family + ' ' + face.weight);
      return seen;
    }

    unique += 1;
    const name = face.family.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + unique + '.woff2';
    fs.writeFileSync(path.join(outDir, name), data);
    byUrl.set(face.url, name);
    byHash.set(hash, name);
    console.log('downloaded fonts/' + name + ' (' + data.length + ' bytes)');
    return name;
  }

  let out = '/* Auto-generated by scripts/fetch-fonts.js — do not edit by hand. */\n';
  for (const face of faces) {
    const name = await fileFor(face);
    out += '@font-face {\n';
    out += '  font-family: "' + face.family + '";\n';
    out += '  src: url("' + name + '") format("woff2");\n';
    out += '  font-weight: ' + face.weight + ';\n';
    out += '  font-style: ' + face.style + ';\n';
    if (face.range) out += '  unicode-range: ' + face.range + ';\n';
    out += '}\n';
  }
  fs.writeFileSync(path.join(outDir, 'fonts.css'), out);
  console.log('wrote fonts/fonts.css with ' + faces.length + ' faces over ' + unique + ' files');
})().catch((e) => { console.error(e); process.exit(1); });
